### ISSUE TITLE
Example using vite-plugin-ssr does not work

### ISSUE THREAD

**Issue by mdixon4** [vikejs/telefunc#16]
To reproduce, initialise the vite-plugin-ssr example as indicated in the README.

```
git clone git@github.com:vikejs/telefunc
cd telefunc/examples/vite-plugin-ssr/
npm install
npm run dev
```

Then try to add a todo item. The server provides an error:

```
Error: Cannot find module '/home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/vite/../../..//node/vite/importTelefuncFiles.ts'
Require stack:
- /home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/utils/nodeRequire.js
- /home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/utils/index.js
- /home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/server/runTelefunc/assertHttpRequest.js
- /home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/server/telefunc.js
- /home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/server/index.js
- /home/matt/code/telefunc/examples/vite-plugin-ssr/server/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at loadViteEntry (/home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/vite/loadViteEntry.js:15:39)
    at loadTelefuncFilesWithVite (/home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/vite/loadTelefuncFilesWithVite.js:14:67)
    at loadTelefuncFiles (/home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/server/runTelefunc/loadTelefuncFiles.js:19:74)
    at runTelefunc_ (/home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/server/runTelefunc.js:60:108)
    at runTelefunc (/home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/server/runTelefunc.js:28:22)
    at telefunc (/home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/telefunc/dist/node/server/telefunc.js:21:42)
    at /home/matt/code/telefunc/examples/vite-plugin-ssr/server/index.js:38:32
    at Layer.handle [as handle_request] (/home/matt/code/telefunc/examples/vite-plugin-ssr/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by brillout** [comment]
Indeed, let me fix this.

**Comment by brillout** [comment]
Run the steps again and it will work.

Let me know if you run into any other problem or if you have any question.

**Comment by mdixon4** [comment]
Indeed I can confirm that fixes the problem. Thanks for your prompt response!
